title: "我的知识库"
description: "探索技术与创意"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

baseurl: ""
url: "https://ljh938527.github.io"
logo: "/assets/logo.png"

lang: "zh-CN"
timezone: "Asia/Shanghai"

collections:
  docs:                    # 集合名称（自定义）
    output: true           # 生成静态页面
    permalink: /docs/:path/ # 控制最终访问路径
    nav-order: 2

defaults:
  - scope:
      path: "_docs"        # 作用范围
      type: "docs"         # 集合类型
    values:
      layout: docs         # 使用专用布局（可选）
      nav_exclude: true    # 排除导航栏