title: "ljh938527 的知识库"
description: "探索技术与创意"
theme: minima
baseurl: ""
url: "https://ljh938527.github.io"
logo: "/assets/logo.png"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

lang: "zh-CN"
timezone: "Asia/Shanghai"

collections:
  docs:
    output: true
    permalink: /docs/:path/
    nav-order: 2

defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      nav_exclude: true
      layout: docs
  - scope:
      path: "_docs/index.md"
    values:
      nav_exclude: false

minima:
  navigation:
    - title: "主页"
      url: /
    - title: "文档中心"
      url: /docs/
