title: "我的知识库"
description: "探索技术与创意"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

baseurl: ""
url: "https://ljh938527.github.io"
logo: "/assets/logo.png"

lang: "zh-CN"
timezone: "Asia/Beijing"

collections:
  changelog:
    output: true
    permalink: /changelog/:title/